// Generated by CoffeeScript 1.9.2
$(function() {
  var animalArray, assignSpecies;
  animalArray = [];
  $("#animal").submit(function(e) {
    var formData;
    e.preventDefault();
    formData = $("#animal :input").serializeArray();
    console.log(formData);
    return assignSpecies(formData);
  });
  assignSpecies = function(animal) {
    var newAnimal;
    if ($('#batman').val() === "mammal") {
      newAnimal = new Mammal(animal[0].value);
      return newAnimal.legs(animal[2].value);
    } else if ($('#batman').val() === "avian") {
      newAnimal = new Avian(animal[0].value);
      return newAnimal.legs(animal[2].value);
    } else {
      newAnimal = new Reptile(animal[0].value);
      return newAnimal.legs(animal[2].value);
    }
  };
  return console.log("DOM...inated");
});
