// Generated by CoffeeScript 1.9.2
var runHandlebar;

runHandlebar = function() {
  var compiledHtml, context, template, templateScript;
  templateScript = $("#animal-name-template").html();
  template = Handlebars.compile(templateScript);
  context = {
    "name": $("#batman").val()
  };
  return compiledHtml = template(context);
};
